---
# install kubernetes
- name: Install dependencies
  apt_rpm:
    update_cache: true
    package:
      - curl
      - nano
      - htop
      - iftop
      - git
      - mc
      - wget
      - python3-module-kubernetes-client
      - bind-utils
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo


- name: Install kubernetes
  apt_rpm:
    update_cache: true
    state: present
#    allow_downgrade: true
    package:
      - kubernetes1.28-kubeadm
      - kubernetes1.28-kubelet
      - kubernetes1.28-crio
      - cri-tools1.28
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo


- name: enable crio
  service: 
    name: crio
    state: started
    enabled: yes
  tags: crio
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo


- name: enable kubelet
  service: 
    name: kubelet
    state: started
    enabled: yes
  tags: kubelet
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo

- name: check config kubeled daemon
  shell: sed -i "s/--cluster-domain=cluster.local/--cluster-domain={{ net_local_domain }}/" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo
  ignore_errors: yes

- name: check config kubeled daemon
  shell: sed -i "s/KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook/KUBELET_AUTHZ_ARGS=--authentication-token-webhook=true --authorization-mode=Webhook/" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo
  ignore_errors: yes

#- name: reload systemd kubelet
#  service: 
#    name: kubelet
#    state: reloaded
#    enabled: yes
#  tags: kubelet
#  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
#  become_method: sudo

- name: restart systemd kubelet
  service: 
    name: kubelet
    state: restarted
    enabled: yes
  tags: kubelet
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo